Create reset-monitors command

diff --git a/nixos/bin/set-monitor b/nixos/bin/set-monitor
--- a/nixos/bin/set-monitor
+++ b/nixos/bin/set-monitor
@@ -1,16 +1,10 @@
 #!/usr/bin/env bash
 
+set -eu
 
 monitor="$1"
 mode="$2"
 pos="${3:-0x0}"
-
-# set-monitor eDP-1-1 2560x1440
-# set-monitor DP-1-3 1920x1080 2560x0
-
-say() {
-    echo "[$(date -Iseconds)] $0"
-}
 
 is_set() {
     local line="$(xrandr -q | grep $monitor)"
@@ -19,18 +13,22 @@ is_set() {
 
 run() {
     for i in $(seq 1 5); do
-        sleep 2
         if is_set; then
             return 0
         fi
-        xrandr --output $monitor --mode $mode --pos $pos
+        if [[ $pos == 0x0 ]]; then
+            xrandr --output $monitor --mode $mode
+        else
+            xrandr --output $monitor --mode $mode --pos $pos
+        fi
+        sleep 2
     done
     return 1
 }
 
-
 if run; then
-    say "Succeeded to set monitor mode."
+    echo "Monitor mode is set:"
+    xrandr -q | grep "$monitor"
 else
-    say "Failed to set monitor mode."
+    echo "Failed to set monitor mode."
 fi
